version: "2.3"
services:
  # cannalysis_api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   expose:
  #     - 8080
  #   depends_on:
  #     - db
  #   networks:
  #     - cannalysis_network
  #   links:
  #     - db
  #   environment:
  #     # Format:
  #     # postgresql://[user[:password]@][netloc][:port][/dbname][?param=value&]
  #     DATABASE_URI: "${DATABASE_URI}"
  db:
    image: postgres:11.7
    mem_limit: 1024MB
    mem_reservation: 1G
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-root}"
    ports:
      - "5432:5432"
    networks:
      - cannalysis_network
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data

networks:
  cannalysis_network:
    driver: bridge

volumes:
  db-data:
